### ISSUE TITLE
No solution branch

### ISSUE THREAD

**Issue by mLuby** [AlgorithmsMeetup/GeneticAlgorithms#1]

**Comment by Syeoryn** [comment]
Done!  Check it out and let me know what you think.  Sadly, there are still no tests, and I'm currently trying to decide what to give them and what not to.  Have any ideas how to test it?

**Comment by mLuby** [comment]
Nice! Refactored logging a bit. Agree that integration tests are tricky, but we can test constituent functions pretty easily. Will post ideas on #2 .
