### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by Syeoryn** [AlgorithmsMeetup/GeneticAlgorithms#2]

**Comment by mLuby** [comment]
Unit tests! Let's PR it so we can comment on the code.
- alterRoute: returns a route that is not the route passed in. (and differs in one way?)
- createRoute: returns a route. routes are random (not sure how to test this non-flakily?)
- calculateDistance: returns total great circle distances of a route of {lat, long} objects.
- distanceCalculator: returns great circle distance between two {latitude, longitude} objects.

**Comment by Syeoryn** [comment]
Complete!
