### ISSUE TITLE
Bug --- Solution does not work. 

### ISSUE THREAD

**Issue by arunsivasankaran** [AlgorithmsMeetup/GeneticAlgorithms#7]
## BUGS
- log.js is not being loaded in SpecRunner.html
- log.js uses the require.

**Comment by mLuby** [comment]
Thanks; your [PR](https://github.com/AlgorithmsMeetup/GeneticAlgorithms/commit/5fe618d873f2b2101160c203cdfb3b3518ecfc4b) fixes.
